### ISSUE TITLE
Layout sidebar mode

### ISSUE THREAD

**Issue by jbcallv** [airiusc/policy-management#51]
Currently the sidebar pushes the page over:
![image](https://user-images.githubusercontent.com/67614219/206153987-b41a6ac0-7d05-456b-862c-277540d8d4fc.png)

On phone screens it does this:
![image](https://user-images.githubusercontent.com/67614219/206154065-b77d1547-0dd0-49e0-8a3a-ea12dac160ac.png)

I think it looks better in phone mode, especially when notifications come up. When the page is pushed right, the notifications don't appear centered. Thoughts? If you agree, let's modify the main layout so the sidebar goes over the page, perhaps even with a shadow

**Comment by kaitlinnnn** [comment]
This is what a notification looks like when:

1. the menu drawer is closed (nice and centered)
<img width="1440" alt="closed" src="https://user-images.githubusercontent.com/60243436/206337023-ec875d9b-6239-480d-b867-2bfd792f2001.png">


2. the menu drawer is open and it slides the page content over (not centered)
<img width="1440" alt="open-slides" src="https://user-images.githubusercontent.com/60243436/206337039-1c6bff2c-5159-4b75-bfb2-8350e1dba31f.png">


3. the menu drawer is open and it overlays the page content (still slightly off-center). This option doesn't seem great either because the drawer hides the header title/logo/menu icon
<img width="1440" alt="open-overlays" src="https://user-images.githubusercontent.com/60243436/206337071-2efa078e-e93b-45bd-85c7-a59593d5b91f.png">

**Comment by kaitlinnnn** [comment]
What if we left the menu drawer as it is (sliding the header and page content over) and move the notification to:

1.  bottom right corner
<img width="1440" alt="bottom-right" src="https://user-images.githubusercontent.com/60243436/206338743-2820ef99-93af-4da0-9202-791c03b34319.png">


2. top right corner
<img width="1440" alt="top-right" src="https://user-images.githubusercontent.com/60243436/206338759-e40ebba2-38fd-4b55-9bee-b9c37706e59e.png">

This still may not be ideal because it temporarily covers text in the header / footer. I'm going to research to see if we can set a custom location on the screen instead of the default positions

**Comment by kaitlinnnn** [comment]
# Default Positions

<img width="833" alt="Screenshot 2022-12-07 at 9 10 00 PM" src="https://user-images.githubusercontent.com/60243436/206339276-d3844c4e-a790-4f31-8382-cf6a039228b2.png">

**Comment by jbcallv** [comment]
> This is what a notification looks like when:
> 
> 1. the menu drawer is closed (nice and centered)
> 
> <img alt="closed" width="1440" src="https://user-images.githubusercontent.com/60243436/206337023-ec875d9b-6239-480d-b867-2bfd792f2001.png">
> 
> 2. the menu drawer is open and it slides the page content over (not centered)
> 
> <img alt="open-slides" width="1440" src="https://user-images.githubusercontent.com/60243436/206337039-1c6bff2c-5159-4b75-bfb2-8350e1dba31f.png">
> 
> 3. the menu drawer is open and it overlays the page content (still slightly off-center). This option doesn't seem great either because the drawer hides the header title/logo/menu icon
> 
> <img alt="open-overlays" width="1440" src="https://user-images.githubusercontent.com/60243436/206337071-2efa078e-e93b-45bd-85c7-a59593d5b91f.png">

for 3, thoughts on adding a smaller logo with smaller "Airius" text as the sidebar menu? also, if we set the layout to phone mode i think it might blur out / put a shadow on the page, which would make it look a bit better
